const FETCH_GAMES = 'FETCH_GAMES'
const CHANGE_PAGE = 'CHANGE_PAGE'
const FETCH_GENRES = 'FETCH_GENRES'
const FILTER_BY_GENRE = 'FILTER_BY_GENRE'
const ORDER_BY = 'ORDER_BY'
const RATE_BY = 'RATE_BY'
const EXIST = 'EXIST'
const PLATFORMS = 'PLATFORMS'
const POST_GAME = 'POST_GAME'
const SEARCH_NAME = 'SEARCH_NAME'

module.exports = {
  FETCH_GAMES,
  CHANGE_PAGE,
  FETCH_GENRES,
  FILTER_BY_GENRE,
  ORDER_BY,
  RATE_BY,
  EXIST,
  PLATFORMS,
  POST_GAME,
  SEARCH_NAME
}